//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetLookup
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StreetData", Namespace="http://schemas.datacontract.org/2004/07/PostalCodeLookup")]
    public partial class StreetData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CityField;
        
        private string CountyField;
        
        private string RoadNameField;
        
        private string TownField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoadName
        {
            get
            {
                return this.RoadNameField;
            }
            set
            {
                this.RoadNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town
        {
            get
            {
                return this.TownField;
            }
            set
            {
                this.TownField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStreetLookup")]
public interface IStreetLookup
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreetLookup/GetStreet", ReplyAction="http://tempuri.org/IStreetLookup/GetStreetResponse")]
    PostalCodeLookup.StreetData GetStreet(string postcode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreetLookup/GetStreet", ReplyAction="http://tempuri.org/IStreetLookup/GetStreetResponse")]
    System.Threading.Tasks.Task<PostalCodeLookup.StreetData> GetStreetAsync(string postcode);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStreetLookupChannel : IStreetLookup, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StreetLookupClient : System.ServiceModel.ClientBase<IStreetLookup>, IStreetLookup
{
    
    public StreetLookupClient()
    {
    }
    
    public StreetLookupClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StreetLookupClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StreetLookupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StreetLookupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public PostalCodeLookup.StreetData GetStreet(string postcode)
    {
        return base.Channel.GetStreet(postcode);
    }
    
    public System.Threading.Tasks.Task<PostalCodeLookup.StreetData> GetStreetAsync(string postcode)
    {
        return base.Channel.GetStreetAsync(postcode);
    }
}
